CREATE DATABASE IF NOT EXISTS bootcamp;
USE bootcamp;
DROP TABLE IF EXISTS users;
CREATE TABLE users(
  id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(50) NOT NULL,
  age INT NOT NULL,
  username VARCHAR(50) NOT NULL UNIQUE,
  email VARCHAR(50) NOT NULL,
  country VARCHAR(20) NOT NULL,
  cp VARCHAR(20) NOT NULL,
  gender ENUM('male', 'female') NOT NULL DEFAULT 'female',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);